config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  devise_for :users, :controllers => {
    omniauth_callbacks: 'omniauth_callbacks',
    registrations: 'users/registrations'
  }

  root 'avisos#index'

  #get 'users/show', as: 'user_root'

  resources :users
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  resources :categories, only: [:index, :show]
  resources :avisos
  resources :communicates, only: [:new, :create, :show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/

  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :lastseenable, :omniauthable, :omniauth_providers => [:twitter]

  has_many :avisos

  ROLES = %w[publisher hunter]


  validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update
  validates :name, :email, presence: true
  validates :name, format: { with: /\A[a-zA-Z]+\z/,
    message: "Se admiten solamente caracteres númericos" }

  def self.find_for_oauth(auth, signed_in_resource = nil)

    # Get the identity and user if they exist
    identity = Identity.find_for_oauth(auth)

    # If a signed_in_resource is provided it always overrides the existing user
    # to prevent the identity being locked with accidentally created accounts.
    # Note that this may leave zombie accounts (with no associated identity) which
    # can be cleaned up at a later date.
    user = signed_in_resource ? signed_in_resource : identity.user

    # Create the user if needed
    if user.nil?

      # Get the existing user by email if the provider gives us a verified email.
      # If no verified email was provided we assign a temporary email and ask the
      # user to verify it on the next step via UsersController.finish_signup
      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email if email_is_verified
      user = User.where(:email => email).first if email

      # Create the user if it's a new registration
      if user.nil?
        user = User.new(
          name: auth.extra.raw_info.name,
          #username: auth.info.nickname || auth.uid,
          email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
          password: Devise.friendly_token[0,20]
        )
        #user.skip_confirmation!
        user.skip_confirmation! if user.respond_to?(:skip_confirmation)
        user.save!
      end
    end

    # Associate the identity with the user if needed
    if identity.user != user
      identity.user = user
      identity.save!
    end
    user
  end

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def create
    @user = User.new(sign_up_params)

    respond_to do |format|
      if @user.save

        if params[:user][:roles] == "publisher"
          @user.add_role :publisher
        else
          @user.add_role :hunter
        end
        @user.save

        # Logear usuario despues de crear registro nuevo
        sign_in(@user, :bypass => true)

        format.html { redirect_to @user, notice: 'La cuenta ya esta lista para usar.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end

  end

private

  def sign_up_params
    params.require(:user).permit( :email, :password, :password_confirmation , :name, :phone, :location)
  end

  def account_update_params
    params.require(:user).permit(:email, :password, :password_confirmation, :current_password , :role, :name, :phone, :location)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :finish_signup]
  before_action :authenticate_user!, except: [:new]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @avisos = @user.avisos
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        sign_in(@user == current_user ? @user : current_user, :bypass => true)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

 # GET/PATCH /users/:id/finish_signup
  def finish_signup
    # authorize! :update, @user
    if request.patch? && params[:user] #&& params[:user][:email]
      if @user.update(user_params)
        #@user.skip_reconfirmation!

        if params[:user][:roles] == "publisher"
          @user.add_role :publisher
        else
          @user.add_role :hunter
        end

        @user.save

        sign_in(@user, :bypass => true)
        #redirect_to @user, notice: 'Your profile was successfully updated.'
        redirect_to root_path, notice: "Tu perfil ha sido creado!"
      else
        @show_errors = true
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      accessible = [ :name, :email, :phone, :location, :role ]
      accessible << [ :password, :password_confirmation ] unless params[:user][:password].blank?
      params.require(:user).permit(accessible)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for user, :html => { :class => "form-horizontal" } do |f| %>
  <% if user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(user.errors.count, "error") %> prohibited
      this article from being saved:</h2>
    <ul>
    <% user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>


  <fieldset>
    <legend class="text-left">Actualizar mis datos:</legend>

    <div class="form-group">
      <%= f.label :name, "Nombre completo:", :class => "control-label col-md-3" %>
      <div class="col-md-9">
        <%= f.text_field :name, :class => "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :phone, "Telefono de contacto:", :class => "control-label col-md-3" %>
      <div class="col-md-9">
        <%= f.text_field :phone, :class => "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :location, "Localidad:", :class => "control-label col-md-3" %>
      <div class="col-md-9">
        <%= f.text_field :location, :class => "form-control" %>
      </div>
    </div>

    <!-- Form actions -->
    <div class="form-group">
      <div class="col-md-12 text-center">
      <%= f.submit "Actualizar mis datos", :class => "btn btn-primary btn-sm" %>
      </div>
    </div>


  </fieldset>
<% end %>

app/views/users/edit.html.erb
<%= content_tag(:h3, "Bienvenido,  #{@user.name}") %>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= render 'form', user: @user %>
  </div>
</div>

<% if current_user.has_role? :publisher %>
<div class="text-center add_more_separation">
 <%= link_to 'Mis Avisos', @user, :class => "btn btn-sm btn-primary" %>
</div>
<% end %>

app/views/users/finish_signup.html.erb
<h3>Terminar registro:</h3>
<%= form_for(current_user, :as => 'user', :url => finish_signup_path(current_user), :html => { role: 'form', :class => "form-horizontal" }) do |f| %>
    <% if @show_errors && current_user.errors.any? %>
      <div id="error_explanation">
        <% current_user.errors.full_messages.each do |msg| %>
          <%= msg %><br>
        <% end %>
      </div>
    <% end %>

  <fieldset>
    <legend class="text-left">Agregar Email:</legend>

    <div class="form-group">
      <%= f.label :email, "Email:", :class => "control-label col-md-3" %>
      <div class="col-md-9">
        <%= f.email_field :email, :autofocus => true, :value => '', :class => "form-control" %>
      </div>
    </div>
  </fieldset>

  <fieldset>
    <legend>Seleccionar tipo de cuenta:</legend>

    <div class="form-group">
    <%= f.collection_select :roles, User::ROLES, :to_s, :humanize, {}, {:class => "form-control"} %>
    </div>
  </fieldset>

    <div class="actions">
      <%= f.submit 'Continuar', :class => 'btn btn-primary' %>
    </div>

<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<%= content_tag(:h3, "Avisos de  #{@user.name}") %>
<%= content_tag(:h5, "Localidad: #{@user.location}") %>

<div class="row">
<%= render "application/avisos_grid", avisos: @avisos %>
</div>