config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  devise_for :users, :controllers => {
    omniauth_callbacks: 'omniauth_callbacks',
    registrations: 'users/registrations'
  }

  root 'avisos#index'

  #get 'users/show', as: 'user_root'

  resources :users
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  resources :categories, only: [:index, :show]
  resources :avisos
  resources :communicates, only: [:new, :create, :show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :ensure_signup_complete, only: [:new, :create, :update, :destroy]


  def after_sign_in_path_for(resource)
    #current_user_path
    root_path
  end

  def after_sign_out_path_for(resource_or_scope)
    request.referrer
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update) { |u|
      u.permit(:password, :password_confirmation, :current_password)
    }
  end

  def ensure_signup_complete
    # Ensure we don't go into an infinite loop
    return if action_name == 'finish_signup'

    # Redirect to the 'finish_signup' page if the user
    # email hasn't been verified yet
    if current_user && !current_user.email_verified?
      redirect_to finish_signup_path(current_user)
    end
  end

  rescue_from CanCan::AccessDenied do |exception|
    flash[:error] = exception.message
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissible", role: 'alert') do
        concat(content_tag(:button, class: 'close', data: { dismiss: 'alert' }) do
          concat content_tag(:span, '&times;'.html_safe, 'aria-hidden' => true)
          concat content_tag(:span, 'Cerrar', class: 'sr-only')
        end)
        concat message
      end)
    end
    nil
  end

  def title(page_title)
    content_for(:title) { page_title }
  end
end

app/views/application/_avisos_grid.html.erb
<% avisos.each do |aviso| %>
  <div class="col-md-4">
      <%#= image_tag aviso.photo.url(:medium) %>
      <%= image_tag(aviso.photo.url(:medium) , :alt => "", :width => 280, :height => 220) %>

      <div class="caption">
        <%= content_tag(:h5, aviso.title) %>

        <p>
          <%= link_to "Contactar", aviso, :class => "btn btn-sm btn-default" %>
          <% if current_user.present?  %>
          <%= link_to 'Editar', edit_aviso_path(aviso), :class => "btn btn-sm btn-danger" if current_user.has_role? :publisher %>
          <% end %>
        </p>
      </div>
  </div>
<% end %>

app/views/application/_categories.html.erb
<ul class="list-group">
<% categories_list.each do |cat| %>
  <li class="list-group-item">
    <%= content_tag(:span, cat.avisos.count, :class => "badge") %>
    <%= link_to cat.name.capitalize, category_path(cat) %>
  </li>
<% end %>
</ul>

app/views/application/_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top add_shadow">
  <div class="container">
    <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

        <%= link_to root_path, :class => 'navbar-brand' do %>
        <span class="glyphicon glyphicon-home" aria-hidden="true"></span> &nbsp; SuperAvisos
        <% end %>

    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

    <ul class="nav navbar-nav navbar-left">

      <li>
        <%= link_to avisos_path do %>
        <span class="glyphicon glyphicon-bookmark" aria-hidden="true"></span> &nbsp; Ver avisos
        <% end %>
      </li>

      <% if user_signed_in? && (current_user.has_role? :publisher) %>
      <li>
        <%= link_to new_aviso_path do %>
        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span> &nbsp; Publicar
        <% end %>
      </li>
      <% end %>
    </ul>

    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
      <% if current_user.has_role? :publisher %>
      <li>
        <%= link_to current_user do %>
        <span class="glyphicon glyphicon-th-large" aria-hidden="true"></span> &nbsp; Mis Avisos
        <% end %>
      </li>
      <% end %>
      <li>
        <%= link_to edit_user_path(current_user) do %>
        <span class="glyphicon glyphicon-user" aria-hidden="true"></span> &nbsp; Mis Datos
        <% end %>
      </li>
      <li>
        <%= link_to 'Salir', destroy_user_session_path, :method => :delete %>
      </li>
      <% else %>
      <li>
        <%= link_to 'Entrar', new_user_session_path %>
      </li>
      <li>
        <%= link_to 'Nueva Cuenta', new_user_registration_path %>
      </li>
      <% end %>
    </ul>

    </div><!-- /.navbar-collapse -->
  </div>
</nav>